version: "3"
services:
  base:
    build:
      context: ..
      dockerfile: system/Dockerfile
      target: base
    volumes:
      - type: bind
        source: ../../config.ini
        target: /config.ini
    env_file: ../../.env
    networks:
      - internal_net
