version: "3"
name: infra
services:
  input:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: input
    networks:
      - distribuidos-tp2_outside_net
      - distribuidos-tp2_internal_net
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    depends_on:
      parsers:
        condition: service_healthy

  parsers:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: parsers
    deploy:
      mode: replicated
      replicas: ${PARSERS_SCALE}
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    depends_on:
      rain-joiners:
        condition: service_healthy
      city-joiners:
        condition: service_healthy
      year-joiners:
        condition: service_healthy

  rain-joiners:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: joiners/rain
      target: joiners
    deploy:
      mode: replicated
      replicas: ${RAIN_JOINERS_SCALE}
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    depends_on:
      rain-aggregators:
        condition: service_healthy

  city-joiners:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: joiners/city
      target: joiners
    deploy:
      mode: replicated
      replicas: ${CITY_JOINERS_SCALE}
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    depends_on:
      city-aggregators:
        condition: service_healthy

  year-joiners:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: joiners/year
      target: joiners
    deploy:
      mode: replicated
      replicas: ${YEAR_JOINERS_SCALE}
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    depends_on:
      year-aggregators:
        condition: service_healthy

  rain-aggregators:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: aggregators/rain
      target: aggregators
    deploy:
      mode: replicated
      replicas: ${RAIN_AGGREGATORS_SCALE}
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini

  city-aggregators:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: aggregators/city
      target: aggregators
    deploy:
      mode: replicated
      replicas: ${CITY_AGGREGATORS_SCALE}
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini

  year-aggregators:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: aggregators/year
      target: aggregators
    deploy:
      mode: replicated
      replicas: ${YEAR_AGGREGATORS_SCALE}
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini

  rain-reducer:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: reducers/rain
      target: reducers
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini

  city-reducer:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: reducers/city
      target: reducers
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini

  year-reducer:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: reducers/year
      target: reducers
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini

  output:
    extends:
      file: src/system/compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: output
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    networks:
      - distribuidos-tp2_outside_net
      - distribuidos-tp2_internal_net

  client:
    build:
      dockerfile: ./src/client/Dockerfile
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
      - type: bind
        source: src/client/data
        target: /tmp/data
      - type: bind
        source: src/client/results
        target: /tmp/results
    networks:
      - distribuidos-tp2_outside_net

networks:
  distribuidos-tp2_internal_net:
    external: true
  distribuidos-tp2_outside_net:
    external: true
